/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AplicaRouteImport } from './routes/aplica'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComunitatiIdRouteImport } from './routes/comunitati.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AplicaRoute = AplicaRouteImport.update({
  id: '/aplica',
  path: '/aplica',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunitatiIdRoute = ComunitatiIdRouteImport.update({
  id: '/comunitati/$id',
  path: '/comunitati/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aplica': typeof AplicaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/comunitati/$id': typeof ComunitatiIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aplica': typeof AplicaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/comunitati/$id': typeof ComunitatiIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aplica': typeof AplicaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/comunitati/$id': typeof ComunitatiIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aplica' | '/sitemap.xml' | '/comunitati/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aplica' | '/sitemap.xml' | '/comunitati/$id'
  id: '__root__' | '/' | '/aplica' | '/sitemap.xml' | '/comunitati/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AplicaRoute: typeof AplicaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ComunitatiIdRoute: typeof ComunitatiIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aplica': {
      id: '/aplica'
      path: '/aplica'
      fullPath: '/aplica'
      preLoaderRoute: typeof AplicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunitati/$id': {
      id: '/comunitati/$id'
      path: '/comunitati/$id'
      fullPath: '/comunitati/$id'
      preLoaderRoute: typeof ComunitatiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AplicaRoute: AplicaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ComunitatiIdRoute: ComunitatiIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
