/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProiecteRouteImport } from './routes/proiecte'
import { Route as PoliticaDeConfidentialitateRouteImport } from './routes/politica-de-confidentialitate'
import { Route as ParteneriRouteImport } from './routes/parteneri'
import { Route as DespreNoiRouteImport } from './routes/despre-noi'
import { Route as DepartamenteRouteImport } from './routes/departamente'
import { Route as AplicaRouteImport } from './routes/aplica'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComunitatiIdRouteImport } from './routes/comunitati.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProiecteRoute = ProiecteRouteImport.update({
  id: '/proiecte',
  path: '/proiecte',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeConfidentialitateRoute =
  PoliticaDeConfidentialitateRouteImport.update({
    id: '/politica-de-confidentialitate',
    path: '/politica-de-confidentialitate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ParteneriRoute = ParteneriRouteImport.update({
  id: '/parteneri',
  path: '/parteneri',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreNoiRoute = DespreNoiRouteImport.update({
  id: '/despre-noi',
  path: '/despre-noi',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartamenteRoute = DepartamenteRouteImport.update({
  id: '/departamente',
  path: '/departamente',
  getParentRoute: () => rootRouteImport,
} as any)
const AplicaRoute = AplicaRouteImport.update({
  id: '/aplica',
  path: '/aplica',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunitatiIdRoute = ComunitatiIdRouteImport.update({
  id: '/comunitati/$id',
  path: '/comunitati/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aplica': typeof AplicaRoute
  '/departamente': typeof DepartamenteRoute
  '/despre-noi': typeof DespreNoiRoute
  '/parteneri': typeof ParteneriRoute
  '/politica-de-confidentialitate': typeof PoliticaDeConfidentialitateRoute
  '/proiecte': typeof ProiecteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/comunitati/$id': typeof ComunitatiIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aplica': typeof AplicaRoute
  '/departamente': typeof DepartamenteRoute
  '/despre-noi': typeof DespreNoiRoute
  '/parteneri': typeof ParteneriRoute
  '/politica-de-confidentialitate': typeof PoliticaDeConfidentialitateRoute
  '/proiecte': typeof ProiecteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/comunitati/$id': typeof ComunitatiIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aplica': typeof AplicaRoute
  '/departamente': typeof DepartamenteRoute
  '/despre-noi': typeof DespreNoiRoute
  '/parteneri': typeof ParteneriRoute
  '/politica-de-confidentialitate': typeof PoliticaDeConfidentialitateRoute
  '/proiecte': typeof ProiecteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/comunitati/$id': typeof ComunitatiIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aplica'
    | '/departamente'
    | '/despre-noi'
    | '/parteneri'
    | '/politica-de-confidentialitate'
    | '/proiecte'
    | '/sitemap.xml'
    | '/comunitati/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aplica'
    | '/departamente'
    | '/despre-noi'
    | '/parteneri'
    | '/politica-de-confidentialitate'
    | '/proiecte'
    | '/sitemap.xml'
    | '/comunitati/$id'
  id:
    | '__root__'
    | '/'
    | '/aplica'
    | '/departamente'
    | '/despre-noi'
    | '/parteneri'
    | '/politica-de-confidentialitate'
    | '/proiecte'
    | '/sitemap.xml'
    | '/comunitati/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AplicaRoute: typeof AplicaRoute
  DepartamenteRoute: typeof DepartamenteRoute
  DespreNoiRoute: typeof DespreNoiRoute
  ParteneriRoute: typeof ParteneriRoute
  PoliticaDeConfidentialitateRoute: typeof PoliticaDeConfidentialitateRoute
  ProiecteRoute: typeof ProiecteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ComunitatiIdRoute: typeof ComunitatiIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proiecte': {
      id: '/proiecte'
      path: '/proiecte'
      fullPath: '/proiecte'
      preLoaderRoute: typeof ProiecteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-confidentialitate': {
      id: '/politica-de-confidentialitate'
      path: '/politica-de-confidentialitate'
      fullPath: '/politica-de-confidentialitate'
      preLoaderRoute: typeof PoliticaDeConfidentialitateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parteneri': {
      id: '/parteneri'
      path: '/parteneri'
      fullPath: '/parteneri'
      preLoaderRoute: typeof ParteneriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre-noi': {
      id: '/despre-noi'
      path: '/despre-noi'
      fullPath: '/despre-noi'
      preLoaderRoute: typeof DespreNoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departamente': {
      id: '/departamente'
      path: '/departamente'
      fullPath: '/departamente'
      preLoaderRoute: typeof DepartamenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aplica': {
      id: '/aplica'
      path: '/aplica'
      fullPath: '/aplica'
      preLoaderRoute: typeof AplicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunitati/$id': {
      id: '/comunitati/$id'
      path: '/comunitati/$id'
      fullPath: '/comunitati/$id'
      preLoaderRoute: typeof ComunitatiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AplicaRoute: AplicaRoute,
  DepartamenteRoute: DepartamenteRoute,
  DespreNoiRoute: DespreNoiRoute,
  ParteneriRoute: ParteneriRoute,
  PoliticaDeConfidentialitateRoute: PoliticaDeConfidentialitateRoute,
  ProiecteRoute: ProiecteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ComunitatiIdRoute: ComunitatiIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
